title: Laura Fennelly
logo: /assets/img/Laura.png
description: |
  text below image  

  - ğŸ”— [LinkedIn](https://www.linkedin.com/in/yourprofile)  
  - ğŸ“§ [Email](mailto:your@email.com)  
  - ğŸ“‚ [Resume](https://yourwebsite.com/resume.pdf)  
#show_downloads: true
theme: jekyll-theme-minimal
additional_info: "ğŸ“ Location: New York, USA"



#theme: minimal-mistakes-jekyll
#children:
  #title: "Quick-Start Guide"
  #url: https://drive.google.com/drive/folders/1lPCjBbSbo1bZl0MKw0PZHmWTV7peQFtB
